version: "3.9"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tailtracker
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d tailtracker"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: ./firebaseAdminKey.json
      DATABASE_URL: postgres://root:root@db:5432/tailtracker
    ports:
      - "4000:4000"
    restart: always
    volumes:
      - ./firebaseAdminKey.json:/app/firebaseAdminKey.json:ro

volumes:
  pgdata:
